### ISSUE TITLE
Make template for GitHub actions

### ISSUE THREAD

**Issue by onekiloparsec** [P0ppoff/vue-cli-plugin-ci#1]
😎

**Comment by abskmj** [comment]
I can pick this up. I went through other templates in the repo. What would be the trigger for the workflow?

**Comment by P0ppoff** [comment]
Let's start the more simple as possible. We can trigger the workflow on a new commit ? Does it look smart for new project ? I have any experience with github actions. Can you show me that the config file work or inside the PR description can you explain me how to make it work on a example project ? 
Thanks @abskmj for taking time to contribute ! 🤩

**Comment by abskmj** [comment]
Trigger on new commit sounds like a good starting point. The Github action workflow should be available at a folder path `.github/workflows`. Let me start a draft PR with a version of the template and we can work from there.

A sample workflow that I use for one of my NPM packages is at https://github.com/abskmj/gridfile. It's just for reference.

**Comment by abskmj** [comment]
I have opened a PR #5, can you take a look?

**Comment by P0ppoff** [comment]
Nice, I will look this evening, after work @abskmj
